name:  Exec tests

on:
  workflow_dispatch:
    inputs:
      outOfProc:
        required:  true
        default:  true
        description:  'Execute Mirror Lake Kusto out-of-proc:  true or false'

jobs:
  linux:
    runs-on: ubuntu-latest
    
    env:
      # See OS catalog here:  https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
      dotnetOs:  linux-x64
      exec:  delta-kusto
      dbPrefix:  github_linux_

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore
    - name: Install dependencies
      shell:  bash
      run: dotnet restore code
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build
    - name: Build
      shell:  bash
      run: dotnet build code --configuration Release --no-restore
    # See https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#user-experience
    # & https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file
    # & https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
    - name: Build single file executable
      shell:  bash
      run: |
        dotnet publish code/mirror-lake-kusto -c release -r $dotnetOs \
          -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:PublishTrimmed=true -p:PublishReadyToRun=true \
          -o bin
    # Set environment variables
    - name: Set environment variables
      shell:  bash
      run: |
        echo "mlkIngestionUri=${{ secrets.mlkIngestionUri }}" >> $GITHUB_ENV
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test
    - name: ADX-based integration tests (out-of-proc)
      shell:  bash
      run: |
        dotnet test code/MirrorLakeKustoTest \
        --configuration Release --no-build --verbosity normal
